Repository part4-project/effi_frontend, pull requests merged in 2024-06, with the labels that each got.

#55 그룹 홈 ui 디자인 적용
  src/assets/icons/arrow-down.svg
  src/assets/icons/arrow-left.svg
  src/assets/icons/group-leader-badge.svg
  src/assets/icons/kebab.svg
  src/assets/icons/meeting-live-character.svg
  src/assets/icons/meeting-reserve-chracter.svg
  src/assets/icons/plus-monitor.svg
  src/assets/icons/setting.svg
  src/constants/mockdata.ts
  src/constants/mockdata.type.ts
  src/pages/group-home/components/group-home-header.tsx
  src/pages/group-home/components/group-home-sidebar.tsx
  src/pages/group-home/components/meeting-note-item.tsx
  src/pages/group-home/components/meeting-notes.tsx
  src/pages/group-home/components/meetings.tsx
  src/pages/group-home/index.tsx
  src/pages/group-home/utils/.gitkeep
  src/pages/group-home/utils/completed-percentage-calculate.ts
  src/styles/colors.ts
  src/styles/myReset.ts
  src/styles/z-index.ts
Labels: Page, UI

#60 로그인페이지 디자인변경사항 적용
  src/assets/logo.svg
  src/pages/login/index.tsx
Labels: Page, UI, Refactor

#61 feat: 리포트 모달 디자인 UI 적용 및 회의 안건, 채팅 컴포넌트 공용컴포넌트화 작업 완료
  src/assets/icons/check.svg
  src/assets/icons/circle-blue1.svg
  src/assets/icons/circle-blue5.svg
  src/assets/icons/circle-gray.svg
  src/assets/icons/x-circle.svg
  src/components/.gitkeep
  src/components/meeting/chatting-box.tsx
  src/components/meeting/topic-list.tsx
  src/components/modal/modal-header.tsx
  src/components/modal/modal.tsx
  src/constants/mockdata.ts
  src/pages/group-home/components/report-modal/report-chat-history.tsx
  src/pages/group-home/components/report-modal/report-member.tsx
  src/pages/group-home/components/report-modal/report-modal.tsx
  src/pages/group-home/components/report-modal/report-time.tsx
  src/pages/group-home/components/report-modal/report-topic.tsx
  src/pages/group-home/utils/format-hours-ampm.ts
  src/pages/group-home/utils/time-calculate.ts
Labels: Component, UI, Modal

#62 그룹 홈 디자인 세부 수정 및 회의록 필터 기능 추가
  src/assets/default-profile.jpg
  src/assets/icons/polygon-top.svg
  src/constants/mockdata.ts
  src/pages/group-home/components/date-range-calendar.tsx
  src/pages/group-home/components/group-home-header.tsx
  src/pages/group-home/components/meeting-note-item.tsx
  src/pages/group-home/components/meeting-notes.tsx
  src/pages/group-home/components/meetings.tsx
  src/pages/group-home/index.tsx
  src/pages/group-home/utils/date-range-filter.ts
  src/styles/myReset.ts
Labels: Page, UI

#67 그룹관리 모달 디자인 적용 및 모달하단버튼 공용컴포넌트로 분리
  src/components/modal/modal-button.tsx
  src/pages/group-home/components/group-modal/group-invite.tsx
  src/pages/group-home/components/group-modal/group-member-info.tsx
  src/pages/group-home/components/group-modal/group-member-list.tsx
  src/pages/group-home/components/group-modal/group-modal.tsx
Labels: UI, Refactor, Modal

#66 그룹 홈 미팅box 디자인 수정 및 로직 추가
  src/assets/icons/meeting-no-data-character.svg
  src/pages/group-home/components/meeting-box.tsx
  src/pages/group-home/components/meetings.tsx
  src/pages/group-home/index.tsx
Labels: Component, UI

#70 미팅룸 내 채팅창, 토픽 높이 수정
  src/pages/meeting-room/components/chatting.tsx
  src/pages/meeting-room/components/topics.tsx
Labels: UI

#76 하드코딩된 색상코드 팔레트적용
  src/components/meeting/chatting-box.tsx
  src/components/meeting/chatting-list.tsx
  src/components/meeting/modify-delete-button.tsx
  src/components/meeting/topic-list.tsx
  src/components/meeting/topic.tsx
  src/components/modal/modal.tsx
  src/pages/group-home/components/date-range-calendar.tsx
  src/pages/group-home/components/group-home-sidebar.tsx
  src/pages/group-home/components/group-modal/group-invite.tsx
  src/pages/group-home/components/group-modal/group-member-info.tsx
  src/pages/group-home/components/meeting-note-item.tsx
  src/pages/group-home/components/report-modal/report-member.tsx
  src/pages/group-home/components/report-modal/report-time.tsx
  src/pages/lobby/components/dropdown-button.tsx
  src/pages/lobby/components/my-calendar.tsx
  src/pages/lobby/components/my-schedule-list.tsx
  src/pages/lobby/components/quick-button.tsx
  src/pages/lobby/index.tsx
  src/pages/meeting-room/components/chatting.tsx
  src/pages/meeting-room/components/input-form.tsx
  src/pages/meeting-room/components/timer.tsx
  src/pages/meeting-room/components/topics.tsx
Labels: Refactor

#81 확인 모달 컴포넌트 추가
  src/components/modal/confirm-modal/confirm-modal.tsx
  src/components/modal/modal.tsx
  src/hooks/.gitkeep
  src/pages/group-home/components/group-modal/group-modal.tsx
Labels: UI, Modal

#79 그룹 생성 모달 임시 디자인 적용
  src/pages/side-bar/components/group-item.tsx
  src/pages/side-bar/components/modal/group-create-modal.tsx
Labels: UI, Modal

#80 Feat: 회의 생성 및 수정 모달 디자인 UI 및 기초기능 구현
  src/components/meeting/chatting-box.tsx
  src/components/meeting/topic-list.tsx
  src/components/meeting/topic.tsx
  src/components/modal/modal.tsx
  src/constants/mockdata.ts
  src/pages/group-home/components/meeting-modal/dropdown-selector.tsx
  src/pages/group-home/components/meeting-modal/meeting-form.tsx
  src/pages/group-home/components/meeting-modal/meeting-modal.tsx
  src/pages/group-home/components/report-modal/report-chatting-box.tsx
  src/pages/group-home/components/report-modal/report-modal.tsx
  src/pages/group-home/components/report-modal/report-topic-list.tsx
  src/pages/group-home/utils/format-date-to-string.ts
Labels: UI, Modal

#89 nav바 side바 그룹모달 css리펙토링 및 side바 그룹 폰트크기 무한루프 수정
  public/polygon-left.svg
  public/polygon-top-blue.svg
  src/pages/Root.tsx
  src/pages/group-home/components/group-home-header.tsx
  src/pages/group-home/components/group-modal/group-danger.tsx
  src/pages/group-home/components/group-modal/group-invite.tsx
  src/pages/group-home/components/group-modal/group-member-list.tsx
  src/pages/group-home/components/group-modal/group-modal.tsx
  src/pages/nav-bar/components/profile.tsx
  src/pages/nav-bar/index.tsx
  src/pages/side-bar/components/group-item.tsx
  src/pages/side-bar/index.tsx
Labels: Fix, Refactor

#93 그룹 생성 모달 디자인 최종 적용
  src/pages/side-bar/components/modal/group-create-modal.tsx
Labels: UI, Modal

#91 profile 모달, group home 페이지 리팩토링 및 Pretendard 폰트 적용 안되는 이슈 해결
  index.html
  src/components/modal/profile-modal/invited-list.tsx
  src/components/modal/profile-modal/nickname-input.tsx
  src/components/modal/profile-modal/profile-image-input.tsx
  src/components/modal/profile-modal/profile-modal.tsx
  src/components/modal/profile-modal/user-info.tsx
  src/pages/group-home/components/group-home-sidebar.tsx
  src/pages/group-home/components/meetings.tsx
  src/styles/global.ts
  src/styles/myReset.ts
Labels: Refactor

#95 색상 팔레트 추가 적용 및 랜덤 프로필 이미지 적용
  public/default-profile/default-profile1.svg
  public/default-profile/default-profile2.svg
  public/default-profile/default-profile3.svg
  public/default-profile/default-profile4.svg
  public/default-profile/default-profile5.svg
  public/default-profile/default-profile6.svg
  src/components/meeting/chatting-list.tsx
  src/components/meeting/topic.tsx
  src/components/modal/profile-modal/profile-image-input.tsx
  src/constants/mockdata.ts
  src/pages/group-home/components/group-home-sidebar.tsx
  src/pages/group-home/components/group-modal/group-invite.tsx
  src/pages/group-home/components/group-modal/group-member-list.tsx
  src/pages/group-home/components/meeting-modal/meeting-form.tsx
  src/pages/group-home/components/report-modal/report-topic-list.tsx
  src/pages/meeting-room/components/input-form.tsx
  src/pages/meeting-room/index.tsx
  src/styles/colors.ts
  src/utils/get-random-num.ts
Labels: Refactor, Modal

#97 fix: 리포트 모달 css 수정 및 회의 생성 및 수정 컴포넌트 분리와 dnd 구현
  package-lock.json
  package.json
  src/components/modal/modal-header.tsx
  src/pages/group-home/components/meeting-modal/meeting-form/dropdown-selector.tsx
  src/pages/group-home/components/meeting-modal/meeting-form/meeting-date.tsx
  src/pages/group-home/components/meeting-modal/meeting-form/meeting-expected-time.tsx
  src/pages/group-home/components/meeting-modal/meeting-form/meeting-form.tsx
  src/pages/group-home/components/meeting-modal/meeting-form/meeting-submit-button-box.tsx
  src/pages/group-home/components/meeting-modal/meeting-form/meeting-title-input.tsx
  src/pages/group-home/components/meeting-modal/meeting-form/meeting-topic-add-box.tsx
  src/pages/group-home/components/meeting-modal/meeting-form/meeting-topic-list.tsx
  src/pages/group-home/components/meeting-modal/meeting-modal.tsx
  src/pages/group-home/components/report-modal/report-chatting-box.tsx
  src/pages/group-home/components/report-modal/report-modal.tsx
  src/pages/group-home/components/report-modal/report-topic-list.tsx
  src/pages/group-home/utils/round-to-15minutes.ts
Labels: UI, Fix, Refactor, Modal

#90 모달 수정
  .gitignore
  package-lock.json
  src/components/modal/confirm-modal/confirm-modal.tsx
  src/components/modal/modal-header.tsx
  src/components/modal/modal.tsx
  src/components/modal/profile-modal/profile-modal-button.tsx
  src/components/modal/profile-modal/profile-modal.tsx
  src/pages/group-home/components/group-home-header.tsx
  src/pages/group-home/components/group-modal/group-modal-button.tsx
  src/pages/group-home/components/group-modal/group-modal.tsx
  src/pages/group-home/components/meeting-modal/meeting-modal-button.tsx
  src/pages/group-home/components/meeting-modal/meeting-modal.tsx
  src/pages/group-home/components/meeting-note-item.tsx
  src/pages/group-home/components/report-modal/report-modal-button.tsx
  src/pages/group-home/components/report-modal/report-modal.tsx
  src/pages/lobby/components/group-list-item.tsx
  src/pages/lobby/components/user-info-button.tsx
  src/pages/nav-bar/components/profile.tsx
  src/pages/side-bar/components/modal/group-create-modal-button.tsx
  src/pages/side-bar/components/modal/group-create-modal.tsx
  src/pages/side-bar/index.tsx
Labels: Refactor, Modal

#100 fix: 회의 수정 모달 버튼 보이지 않는 이슈 해결
  src/pages/group-home/components/meetings.tsx
Labels: Fix, Modal

#101 알림 팝오버 디자인 적용
  public/polygon-top-white.svg
  src/assets/icons/meeting-alarm.svg
  src/constants/mockdata.ts
  src/pages/nav-bar/components/alarm-invite.tsx
  src/pages/nav-bar/components/alarm-list.tsx
  src/pages/nav-bar/components/alarm-meeting.tsx
  src/pages/nav-bar/components/alarm-popover.tsx
  src/pages/nav-bar/components/alarm.tsx
  src/pages/nav-bar/hooks/.gitkeep
  src/pages/nav-bar/hooks/use-check-line.ts
  src/pages/side-bar/components/modal/group-create-modal.tsx
  src/styles/z-index.ts
Labels: UI

#107 그룹명 수정 기능 추가
  src/assets/icons/edit.svg
  src/pages/group-home/components/sidebar/group-home-sidebar.tsx
  src/pages/group-home/components/sidebar/group-name-input.tsx
  src/pages/group-home/index.tsx
  src/styles/myReset.ts
Labels: Component

#104 feat: DND 아이콘 추가 및 드래그 영역 수정
  src/assets/icons/dropdown.svg
  src/pages/group-home/components/meeting-modal/meeting-form.tsx
  src/pages/group-home/components/meeting-modal/meeting-form/dropdown-selector.tsx
  src/pages/group-home/components/meeting-modal/meeting-form/meeting-form.tsx
  src/pages/group-home/components/meeting-modal/meeting-form/meeting-topic-list.tsx
Labels: Fix, Modal

#108 토스트 ui component 및 custom hook 추가
  src/components/toast/toast.tsx
  src/components/toast/toaster.tsx
  src/hooks/use-toast.ts
  src/pages/Root.tsx
  src/pages/group-home/components/sidebar/group-name-input.tsx
  src/styles/z-index.ts
Labels: Component, UI

#111 fix: 캘린더 렌더링 이슈 해결
  src/pages/lobby/components/schedule-calendar.tsx
  src/pages/meeting-room/components/room-camera.tsx
Labels: Fix

#113 구글 OAuth 인증 및 인증 토큰 쿠키에 저장
  netflify.toml
  public/_redirects
  src/components/modal/profile-modal/profile-modal.tsx
  src/pages/lobby/api/.gitkeep
  src/pages/lobby/api/google-auth.ts
  src/pages/lobby/index.tsx
  src/pages/login/components/.gitkeep
  src/pages/login/components/google-login-button.tsx
  src/pages/login/index.tsx
  src/utils/cookie.ts
Labels: API

#116 알림없을 때 팝오버 디자인
  public/polygon-top-white.svg
  src/assets/icons/alarm-empty.svg
  src/pages/nav-bar/components/alarm-empty.tsx
  src/pages/nav-bar/components/alarm-list.tsx
  src/pages/nav-bar/components/alarm-popover.tsx
Labels: UI

#118 feat: 회의록 리스트 일자 선택 디자인 변경 및 초기화 기능 추가
  src/assets/icons/arrow-right.svg
  src/assets/icons/calendar.svg
  src/assets/icons/refresh-calendar.svg
  src/assets/icons/refresh.svg
  src/pages/group-home/components/date-range-calendar.tsx
Labels: Component, UI

#114 axios 및 react-query 세팅
  src/api/axios.ts
  src/api/group/group-request.ts
  src/api/group/group-request.type.ts
  src/api/meeting/meeting-request.ts
  src/api/meeting/meeting-request.type.ts
  src/api/topic/topic-request.ts
  src/api/topic/topic-request.type.ts
  src/api/user/user-request.ts
  src/api/user/user-request.type.ts
  src/hooks/react-query/use-query-group.ts
  src/hooks/react-query/use-query-meeting.ts
  src/hooks/react-query/use-query-topic.ts
  src/hooks/react-query/use-query-user.ts
  src/pages/group-home/components/sidebar/group-name-input.tsx
  src/pages/side-bar/components/group-item.tsx
  src/pages/side-bar/components/group-list.tsx
  src/pages/side-bar/components/modal/group-create-modal-button.tsx
  src/pages/side-bar/components/modal/group-create-modal.tsx
Labels: API, Config

#119 사용하지 않는 import 삭제
  src/hooks/react-query/use-query-user.ts
Labels: Fix

#120 pops 명 변경
  src/pages/lobby/components/schedule-list-item.tsx
Labels: Fix

#125 프로필 이미지 업데이트, 기본이미지 프로필 api 연동 완료
  src/components/modal/profile-modal/profile-image-input.tsx
  src/hooks/react-query/use-query-user.ts
Labels: API

#127 닉네임 제한, 랜덤 설정, api 호출
  src/components/modal/profile-modal/nickname-input.tsx
  src/constants/nickname-data.ts
  src/hooks/react-query/use-query-user.ts
  src/hooks/use-validate-text.ts
  src/utils/createRandomNickname.ts
Labels: API, Refactor

#130 초대받은 그룹 조회, 수락, 거절 api 적용 완료
  src/api/group/group-request.ts
  src/api/group/group-request.type.ts
  src/components/modal/profile-modal/invited-list.tsx
  src/hooks/react-query/use-query-group.ts
Labels: API

#133 그룹관련 api
  src/api/axios.ts
  src/api/group/group-request.ts
  src/api/group/group-request.type.ts
  src/hooks/react-query/use-query-group.ts
  src/hooks/react-query/use-query-user.ts
  src/pages/group-home/components/admin-hoc.tsx
  src/pages/group-home/components/group-modal/group-invite.tsx
  src/pages/group-home/components/group-modal/group-member-info.tsx
  src/pages/group-home/components/group-modal/group-member-list.tsx
  src/pages/group-home/components/sidebar/group-home-sidebar.tsx
  src/pages/group-home/components/sidebar/group-name-input.tsx
  src/pages/group-home/index.tsx
  src/pages/lobby/index.tsx
  src/pages/side-bar/components/group-item.tsx
  src/pages/side-bar/components/group-list.tsx
  src/stores/.gitkeep
  src/stores/group/index.ts
  src/stores/group/select-group-slice.ts
Labels: Component, API

#137 닉네임 api 에러 처리, 토스트 에러 시 색상 변경
  src/api/user/user-request.ts
  src/components/modal/profile-modal/nickname-input.tsx
  src/components/toast/toast.tsx
  src/components/toast/toaster.tsx
  src/hooks/react-query/use-query-user.ts
  src/hooks/use-toast.ts
Labels: API, Refactor

#139 캘린더 드랍다운 고정 및 수정사항 적용
  src/pages/lobby/components/dropdown-box.tsx
  src/pages/lobby/components/make-meeting-button.tsx
  src/pages/lobby/components/schedule-calendar.tsx
  src/pages/lobby/components/schedule-list-item.tsx
  src/pages/lobby/hooks/use-calendar-dropdown.ts
Labels: Refactor

#142 각 api 에러핸들링 컨벤션 추가 및 모든 뮤테이션 코드 리펙토링
  src/api/axios.ts
  src/api/group/group-request.ts
  src/api/group/group-request.type.ts
  src/api/meeting/meeting-request.ts
  src/api/user/user-request.ts
  src/api/user/user-request.type.ts
  src/components/modal/profile-modal/nickname-input.tsx
  src/constants/query-key.ts
  src/hooks/react-query/use-query-group.ts
  src/hooks/react-query/use-query-meeting.ts
  src/hooks/react-query/use-query-user.ts
  src/pages/group-home/components/group-modal/group-invite.tsx
  src/pages/group-home/components/group-modal/group-member-info.tsx
  src/pages/group-home/components/sidebar/group-home-sidebar.tsx
  src/pages/group-home/index.tsx
  src/pages/nav-bar/components/alarm.tsx
  src/pages/side-bar/components/group-item.tsx
  src/pages/side-bar/components/modal/group-create-modal-button.tsx
Labels: API, Refactor, Config

#143 드랍다운 보더 css 수정 및 리팩토링
  src/pages/lobby/components/group-list-item.tsx
  src/pages/lobby/components/schedule-calendar.tsx
  src/pages/lobby/components/schedule-list-item.tsx
Labels: UI, Fix

#141 다크모드 수정, confirm 모달 내 정보에 적용
  src/assets/icons/alarm-empty-dark.svg
  src/assets/icons/group-leader-badge-dark.svg
  src/components/modal/confirm-modal/confirm-modal.tsx
  src/components/modal/profile-modal/profile-modal-button.tsx
  src/components/modal/profile-modal/profile-modal.tsx
  src/pages/group-home/components/group-modal/group-modal-button.tsx
  src/pages/group-home/components/group-modal/group-modal.tsx
  src/pages/group-home/components/sidebar/group-home-sidebar.tsx
  src/pages/group-home/components/sidebar/group-name-input.tsx
  src/pages/lobby/components/dropdown-box.tsx
  src/pages/nav-bar/components/alarm-empty.tsx
  src/pages/nav-bar/components/alarm-list.tsx
  src/pages/nav-bar/components/alarm-popover.tsx
  src/pages/nav-bar/components/dark-mode-button.tsx
  src/pages/nav-bar/components/profile.tsx
  src/pages/nav-bar/index.tsx
  src/pages/side-bar/components/group-item.tsx
  src/utils/theme.ts
Labels: Refactor

#147 다크모드 모달 적용
  src/assets/icons/check copy.svg
  src/assets/icons/circle-white.svg
  src/assets/icons/invite-check-dark.svg
  src/assets/icons/invite-reject-dark.svg
  src/assets/icons/x-circle-dark.svg
  src/components/meeting/chatting-list.tsx
  src/components/meeting/topic.tsx
  src/components/modal/confirm-modal/confirm-modal.tsx
  src/components/modal/modal-button.tsx
  src/components/modal/modal-header.tsx
  src/components/modal/modal.tsx
  src/components/modal/profile-modal/invited-list.tsx
  src/components/modal/profile-modal/nickname-input.tsx
  src/components/toast/toast.tsx
  src/pages/group-home/components/group-modal/group-invite.tsx
  src/pages/group-home/components/group-modal/group-member-info.tsx
  src/pages/group-home/components/group-modal/group-member-list.tsx
  src/pages/group-home/components/meeting-modal/meeting-form/meeting-date.tsx
  src/pages/group-home/components/meeting-modal/meeting-form/meeting-expected-time.tsx
  src/pages/group-home/components/meeting-modal/meeting-form/meeting-title-input.tsx
  src/pages/group-home/components/meeting-modal/meeting-form/meeting-topic-add-box.tsx
  src/pages/group-home/components/meeting-modal/meeting-form/meeting-topic-list.tsx
  src/pages/group-home/components/report-modal/report-chatting-box.tsx
  src/pages/group-home/components/report-modal/report-member.tsx
  src/pages/group-home/components/report-modal/report-time.tsx
  src/pages/group-home/components/report-modal/report-topic-list.tsx
  src/pages/group-home/components/sidebar/group-name-input.tsx
  src/pages/lobby/components/schedule-calendar.tsx
  src/pages/side-bar/components/modal/group-create-modal.tsx
  src/utils/theme.ts
Labels: UI

#153 회의 생성 api 적용
  src/api/meeting/meeting-request.ts
  src/components/modal/modal-button.tsx
  src/hooks/react-query/use-query-group.ts
  src/hooks/react-query/use-query-meeting.ts
  src/hooks/react-query/use-query-user.ts
  src/pages/group-home/components/meeting-modal/meeting-form/meeting-form.tsx
  src/pages/group-home/utils/calculate-end-date.ts
  src/pages/group-home/utils/format-date-to-string.ts
Labels: API, Modal

#152 모달 버튼 hover 적용
  src/components/modal/modal-button.tsx
  src/components/modal/profile-modal/invited-list.tsx
  src/components/modal/profile-modal/profile-modal.tsx
  src/pages/group-home/components/group-modal/group-invite.tsx
  src/pages/group-home/components/group-modal/group-modal.tsx
  src/pages/group-home/components/meeting-modal/meeting-form/meeting-topic-add-box.tsx
  src/pages/side-bar/components/group-item.tsx
  src/pages/side-bar/components/modal/group-create-modal.tsx
  src/utils/theme.ts
Labels: UI, Modal

#154 채팅 구현
  package-lock.json
  package.json
  src/Router.tsx
  src/components/meeting/chatting-list.tsx
  src/components/meeting/user-hoc.tsx
  src/constants/socket-type.ts
  src/hooks/react-query/use-query-user.ts
  src/hooks/socket/use-chat-socket.ts
  src/hooks/socket/use-socket.ts
  src/hooks/use-transform-user.ts
  src/pages/Root.tsx
  src/pages/group-home/components/meetings.tsx
  src/pages/group-home/utils/format-hours-ampm.ts
  src/pages/index.ts
  src/pages/meeting-loading/index.tsx
  src/pages/meeting-room/components/chatting.tsx
  src/pages/meeting-room/hooks/use-history-back-block.ts
  src/pages/meeting-room/hooks/use-reload-block.ts
  src/pages/meeting-room/index.tsx
  src/pages/meeting-room/types/index.ts
  src/stores/group/index.ts
  src/stores/group/select-group-slice.ts
  src/stores/meeting/index.ts
  src/stores/meeting/select-meeting-slice.ts
  vite.config.ts
Labels: Component

#156 모달, 토스트 fade in, out 애니메이션 적용
  src/components/modal/modal.tsx
  src/components/toast/toast.tsx
  src/hooks/react-query/use-query-meeting.ts
  src/hooks/react-query/use-query-user.ts
  src/pages/group-home/components/meeting-modal/meeting-form/meeting-topic-list.tsx
Labels: Component, UI, Modal

#160 채팅관련 이슈 수정(리포트모달, 채팅 시간 및 빈값전송 등)
  src/constants/mockdata.ts
  src/hooks/use-transform-user.ts
  src/pages/group-home/components/report-modal/report-chatting-box.tsx
  src/pages/group-home/utils/format-hours-ampm.ts
  src/pages/group-home/utils/time-calculate.ts
  src/pages/meeting-room/components/chatting.tsx
  src/pages/meeting-room/hooks/use-input-form.ts
Labels: Component, Fix

#161 스켈레톤 Ui navbar, sidebar 적용
  src/pages/nav-bar/components/profile-skeleton.tsx
  src/pages/nav-bar/components/profile.tsx
  src/pages/side-bar/components/group-list-skeleton.tsx
  src/pages/side-bar/components/group-list.tsx
  src/styles/skeleton.ts
  src/utils/theme.ts
Labels: UI

#162 스켈레톤 로비-회의 생성 폴더, 그룹홈-사이드바, 프로필 모달-초대받은 그룹 적용
  src/components/modal/profile-modal/group-list-items.tsx
  src/components/modal/profile-modal/invited-group-list-skeleton.tsx
  src/components/modal/profile-modal/invited-list.tsx
  src/components/modal/profile-modal/profile-image-input.tsx
  src/hooks/react-query/use-query-group.ts
  src/pages/group-home/components/skeleton/group-home-sidebar-skeleton.tsx
  src/pages/group-home/components/skeleton/meeting-notes-skeleton.tsx
  src/pages/group-home/components/skeleton/meetings-skeleton.tsx
  src/pages/group-home/index.tsx
  src/pages/lobby/components/make-meeting-button.tsx
  src/pages/lobby/components/my-group-list.tsx
  src/pages/lobby/components/skeleton/group-list-item-skeleton.tsx
  src/pages/side-bar/components/group-list.tsx
  src/styles/skeleton.ts
Labels: UI

#166 로비 캘린더 디자인 시안 대로 수정
  src/pages/lobby/components/schedule-calendar.tsx
Labels: UI, Refactor

#168 그룹명 수정 낙관적 업데이트 적용
  src/hooks/react-query/use-query-group.ts
  src/pages/group-home/components/sidebar/group-home-sidebar.tsx
  src/pages/group-home/components/sidebar/group-name-input.tsx
Labels: Component, Fix

#169 404 페이지 추가 및 로딩 페이지 디자인 적용
  src/Router.tsx
  src/api/axios.ts
  src/assets/icons/404-door-dark.svg
  src/assets/icons/404-door.svg
  src/assets/icons/404-icon-dark.svg
  src/assets/icons/404-icon.svg
  src/assets/icons/effi-phone-blue.svg
  src/assets/icons/effi-phone-dark.svg
  src/pages/Root.tsx
  src/pages/auth/index.tsx
  src/pages/index.ts
  src/pages/meeting-loading/index.tsx
  src/pages/not-found/index.tsx
  src/utils/theme.ts
Labels: Page, UI

#171 로비 회의 생성 버튼 회의 생성 되게 수정
  src/pages/group-home/components/meeting-modal/meeting-form/meeting-form.tsx
  src/pages/group-home/components/meeting-modal/meeting-modal-button.tsx
  src/pages/lobby/components/group-list-item.tsx
  src/pages/lobby/components/my-group-list.tsx
  src/stores/lobby-group/index.ts
  src/stores/lobby-group/lobby-group-slice.ts
Labels: Fix

#175 navBar 반응형 디자인
  src/pages/Root.tsx
  src/pages/nav-bar/index.tsx
  src/styles/breakpoints.ts
  src/styles/subsection-size.ts
Labels: UI

#172 그룹 탈퇴 및 그룹 멤버 추방
  src/api/axios.ts
  src/api/group/group-request.ts
  src/components/modal/confirm-modal/confirm-modal.tsx
  src/components/modal/modal.tsx
  src/hooks/react-query/use-query-group.ts
  src/pages/group-home/components/group-modal/group-member-info.tsx
  src/pages/group-home/components/group-modal/group-member-list.tsx
  src/pages/group-home/components/group-modal/group-modal.tsx
  src/pages/group-home/components/sidebar/group-home-sidebar.tsx
  src/pages/group-home/components/sidebar/group-leave-modal-button.tsx
  src/pages/group-home/index.tsx
  src/pages/side-bar/components/group-list-skeleton.tsx
  src/pages/side-bar/components/group-list.tsx
  src/pages/side-bar/hooks/.gitkeep
  src/pages/side-bar/utils/.gitkeep
  src/pages/side-bar/utils/group-list-constants.ts
Labels: API

#177 미팅 모달 회의 생성하면 모달 닫히게 수정, 로비 퀵버튼 shadow 추가
  src/pages/group-home/components/meeting-modal/meeting-form/meeting-form.tsx
  src/pages/group-home/components/meeting-modal/meeting-modal.tsx
  src/pages/lobby/components/quick-button.tsx
Labels: UI, Fix

#179 회의 생성 api 적용
  src/api/meeting/meeting-request.ts
  src/hooks/react-query/use-query-meeting.ts
  src/pages/group-home/components/meetings.tsx
  src/pages/group-home/index.tsx
  src/pages/group-home/utils/format-date-to-string.ts
  src/pages/group-home/utils/meeting-box-constants.ts
  src/pages/side-bar/utils/group-list-constants.ts
Labels: API

#183 그룹 홈 회의 주기 변경 및 반응형 구현 (모바일 미완성)
  src/pages/group-home/components/date-range-calendar.tsx
  src/pages/group-home/components/meeting-box.tsx
  src/pages/group-home/components/meeting-note-item.tsx
  src/pages/group-home/components/meeting-notes.tsx
  src/pages/group-home/components/meetings.tsx
  src/pages/group-home/components/sidebar/group-home-sidebar.tsx
  src/pages/group-home/components/skeleton/group-home-sidebar-skeleton.tsx
  src/pages/group-home/components/skeleton/meetings-skeleton.tsx
  src/pages/group-home/hooks/.gitkeep
  src/pages/group-home/hooks/use-check-minute-time.ts
  src/pages/group-home/index.tsx
  src/pages/group-home/utils/format-date-to-string.ts
  src/pages/group-home/utils/meeting-box-constants.ts
  src/styles/z-index.ts
Labels: UI, API

#182 WebRTC n:m 기본 기능 구현
  bower_components/kurento-utils/.bower.json
  bower_components/kurento-utils/.github/PULL_REQUEST_TEMPLATE.md
  bower_components/kurento-utils/LICENSE
  bower_components/kurento-utils/README.md
  bower_components/kurento-utils/bower.json
  bower_components/kurento-utils/js/kurento-utils.js
  bower_components/kurento-utils/js/kurento-utils.map
  bower_components/kurento-utils/js/kurento-utils.min.js
  index.html
  public/bower_components_copy/kurento-utils/.bower.json
  public/bower_components_copy/kurento-utils/.github/PULL_REQUEST_TEMPLATE.md
  public/bower_components_copy/kurento-utils/LICENSE
  public/bower_components_copy/kurento-utils/README.md
  public/bower_components_copy/kurento-utils/bower.json
  public/bower_components_copy/kurento-utils/js/kurento-utils.js
  public/bower_components_copy/kurento-utils/js/kurento-utils.map
  public/bower_components_copy/kurento-utils/js/kurento-utils.min.js
  public/mute-icon.svg
  public/sound/audio-mute.mp3
  public/sound/audio-unmute.mp3
  public/sound/enter-room.mp3
  public/sound/enter.m4a
  public/sound/leave-room.mp3
  public/sound/toast-error.mp3
  public/sound/toast.mp3
  src/assets/icons/camera-off.svg
  src/assets/icons/camera.svg
  src/assets/icons/mic-off.svg
  src/assets/icons/mic.svg
  src/assets/icons/room-out.svg
  src/components/toast/toast.tsx
  src/hooks/use-throttle.ts
  src/pages/auth/index.tsx
  src/pages/group-home/components/meetings.tsx
  src/pages/group-home/index.tsx
  src/pages/meeting-loading/index.tsx
  src/pages/meeting-room/components/chatting.tsx
  src/pages/meeting-room/components/kurento-cameras.tsx
  src/pages/meeting-room/components/room-camera.tsx
  src/pages/meeting-room/index.tsx
  src/pages/meeting-room/kurento/participant.ts
  src/pages/meeting-room/kurento/participants.css
  src/pages/meeting-room/utils/get-ice-servers.ts
  src/utils/play-sound.ts
  src/utils/rtc/kurento-service.ts
Labels: Component, Page, UI, API, Config

#185 다크모드 아이콘 변경 및 로그인 페이지 에피 설명 문구 추가
  public/dark-mode-toggle-btn.svg
  public/light-mode-toggle-btn.svg
  src/pages/login/index.tsx
  src/pages/nav-bar/components/dark-mode-button.tsx
  src/stores/dark-mode/dark-mode-slice.ts
  src/stores/dark-mode/index.ts
  src/styles/colors.ts
  src/utils/theme.ts
Labels: UI

#188 다른 일자에 현재 일자 시간 변경되는 이슈 해결
  src/pages/group-home/components/date-range-calendar.tsx
  src/pages/group-home/components/group-modal/group-member-list.tsx
  src/pages/group-home/components/meeting-modal/meeting-form/meeting-date.tsx
Labels: Fix

#191 design: 회의 수정 아이콘 변경 및 다크모드 색상 변경
  src/pages/group-home/components/meeting-box.tsx
  src/pages/group-home/components/meetings.tsx
Labels: UI

#195 미팅룸에서 초과시간 관련 로직들 추가
  src/api/meeting/meeting-request.ts
  src/hooks/react-query/use-query-meeting.ts
  src/pages/group-home/components/meetings.tsx
  src/pages/meeting-room/components/kurento-cameras.tsx
  src/pages/meeting-room/components/meeting-room-timer.tsx
  src/pages/meeting-room/index.tsx
Labels: Page, API

#196 그룹수정api 구현
  src/api/meeting/meeting-request.ts
  src/api/meeting/meeting-request.type.ts
  src/constants/query-key.ts
  src/hooks/react-query/use-query-meeting.ts
  src/pages/group-home/components/meeting-modal/meeting-form/meeting-form.tsx
  src/pages/group-home/components/meeting-modal/meeting-modal-button.tsx
  src/pages/group-home/components/meeting-modal/meeting-modal.tsx
  src/pages/group-home/components/meetings.tsx
  src/pages/group-home/index.tsx
  src/pages/nav-bar/components/dark-mode-button.tsx
  src/pages/side-bar/components/group-list.tsx
Labels: Component, API

#198 reload 시 다른 사람에게서 peer 비정상적으로 접근되는 이슈 해결
  src/pages/meeting-room/components/kurento-cameras.tsx
Labels: Fix

#193 그룹 홈 모바일 반응형 구현
  src/assets/icons/sidebar-arrow-close-dark.svg
  src/assets/icons/sidebar-arrow-close.svg
  src/assets/icons/sidebar-arrow-dark.svg
  src/assets/icons/sidebar-arrow.svg
  src/pages/Root.tsx
  src/pages/group-home/components/date-range-calendar.tsx
  src/pages/group-home/components/meeting-box.tsx
  src/pages/group-home/components/meeting-note-item.tsx
  src/pages/group-home/components/meeting-notes.tsx
  src/pages/group-home/components/meetings.tsx
  src/pages/group-home/components/sidebar/group-home-sidebar.tsx
  src/pages/group-home/components/skeleton/meetings-skeleton.tsx
  src/pages/group-home/index.tsx
  src/pages/side-bar/components/group-item.tsx
  src/pages/side-bar/components/group-list-skeleton.tsx
  src/pages/side-bar/index.tsx
  src/pages/side-bar/utils/group-list-constants.ts
  src/styles/z-index.ts
  src/utils/theme.ts
Labels: UI

#200 회의 수정버튼 렌더링로직 수정
  src/pages/group-home/components/meetings.tsx
Labels: Fix

#201 sidebar 구분선 추가
  src/pages/group-home/index.tsx
  src/pages/side-bar/index.tsx
  src/pages/side-bar/utils/group-list-constants.ts
Labels: UI, Refactor

#204 리포트 조회 api
  src/api/report/report-request.ts
  src/api/report/report-request.type.ts
  src/components/meeting/user-hoc.tsx
  src/constants/query-key.ts
  src/hooks/react-query/use-query-report.ts
  src/hooks/use-transform-user.ts
  src/pages/group-home/components/meeting-note-item.tsx
  src/pages/group-home/components/report-modal/report-chatting-box.tsx
  src/pages/group-home/components/report-modal/report-chatting-list.tsx
  src/pages/group-home/components/report-modal/report-member.tsx
  src/pages/group-home/components/report-modal/report-modal-button.tsx
  src/pages/group-home/components/report-modal/report-modal.tsx
  src/pages/group-home/components/report-modal/report-time.tsx
  src/pages/group-home/components/report-modal/report-topic-list.tsx
  src/pages/group-home/hooks/use-report-user-mapping.ts
  src/pages/meeting-room/components/chatting-list.tsx
  src/pages/meeting-room/components/chatting.tsx
Labels: API, Modal

#209 report list api 적용 완료
  src/constants/mockdata.type.ts
  src/pages/group-home/components/date-range-calendar.tsx
  src/pages/group-home/components/meeting-note-item.tsx
  src/pages/group-home/components/meeting-notes.tsx
  src/pages/group-home/components/skeleton/meeting-notes-skeleton.tsx
  src/pages/group-home/utils/completed-percentage-calculate.ts
  src/pages/group-home/utils/date-range-filter.ts
  src/pages/group-home/utils/get-current-month-range.ts
Labels: API

#211 title 및 아이콘 설정
  index.html
  public/effi-favicon.svg
Labels: Page

#213 토픽 소켓 구현
  src/api/topic/topic-request.ts
  src/components/meeting/topic.tsx
  src/hooks/react-query/use-query-topic.ts
  src/hooks/socket/use-topic-socket.ts
  src/pages/meeting-room/components/topics.tsx
  src/pages/meeting-room/index.tsx
Labels: Component, API

#216 콘솔로그 제거 및 리포트 시간 개선
  src/components/toast/toast.tsx
  src/hooks/socket/use-alarm-socket.ts
  src/hooks/socket/use-chat-socket.ts
  src/hooks/socket/use-socket.ts
  src/hooks/socket/use-topic-socket.ts
  src/pages/group-home/components/report-modal/report-time.tsx
  src/pages/group-home/utils/time-calculate.ts
  src/pages/meeting-room/components/force-quit-toast.tsx
Labels: Fix, Refactor
