Repository part4-project/effi_frontend, pull requests merged in 2024-07, with the labels that each got.

#223 채팅 하트비트 추가
  src/hooks/socket/use-chat-socket.ts
  src/pages/group-home/components/report-modal/report-chatting-box.tsx
  src/pages/meeting-room/components/chatting.tsx
Labels: Component, Fix

#225 media stream (카메라, 마이크) 변경 기능 완성
  src/assets/icons/screen-share.svg
  src/pages/group-home/components/meeting-modal/meeting-form/meeting-date.tsx
  src/pages/meeting-room/components/kurento-cameras.tsx
  src/pages/meeting-room/components/room-button.tsx
  src/pages/meeting-room/constants/index.ts
  src/pages/meeting-room/kurento/participants.css
  src/pages/meeting-room/types/index.ts
Labels: Component

#227 캘린더 css 분리 및 css 수정
  src/pages/group-home/components/date-range-calendar.tsx
  src/pages/group-home/components/meeting-modal/meeting-form/meeting-date.tsx
  src/pages/lobby/components/schedule-calendar.tsx
  src/styles/calendar.ts
  src/styles/global.ts
Labels: Refactor
